export const LocationsScreens = [
  {
    name: 'Royal Palm Beach',
    clinic: 'Royal Palm Beach Primary & Urgent Care Center',
    address: '11476 Okeechobee Blvd',
    city: 'Royal Palm Beach',
    postalCode: '33411',
    phone: '561-223-8024',
    slug: 'royal-palm-beach-primary-urgent-care-center',
    image: '/royalpalm.jpg',
    subimg: '/doctorgroups.png',
    lat: 26.7054883,
    lng: -80.2249158,
    gmbCid: '16691066410736001367',
    gmbPlaceId: 'ChIJPwCtc_ou2YgRV6FfrneUouc',
    gmbUrl: 'https://www.google.com/maps?cid=16691066410736001367',
    link: 'https://www.google.com/maps?cid=16691066410736001367',
    metaTitle: 'Urgent Care Royal Palm Beach FL | Walk-In Clinic & Primary Care',
    metaDescription: 'Royal Palm Beach urgent care and walk-in clinic. Fast, affordable care for injuries, illness, physicals, and more. No appointment needed. Serving Wellington, Loxahatchee, and 33411.',
    keywords: [
      'urgent care Royal Palm Beach',
      'walk-in clinic Royal Palm Beach',
      'Royal Palm Beach medical clinic',
      'emergency care 33411',
      'primary care Okeechobee Blvd',
      'family doctor Royal Palm Beach',
      'closest urgent care to Wellington',
      'same day doctor appointment Loxahatchee',
      'MD Now alternative Royal Palm Beach'
    ]
  },
  {
    name: 'Lake Worth',
    clinic: 'Lake Worth Primary & Urgent Care Center',
    address: '6447 Lake Worth Rd',
    city: 'Lake Worth Beach',
    postalCode: '33463',
    phone: '561-223-8024',
    slug: 'lake-worth-primary-urgent-care-center',
    image: '/lakeworth.jpg',
    subimg: '/lakeworth2.jpg',
    lat: 26.619606,
    lng: -80.145805,
    gmbCid: '7327887939704951975',
    gmbPlaceId: 'ChIJjen-gjUm2YgRp5T7n0HjsWU',
    gmbUrl: 'https://www.google.com/maps?cid=7327887939704951975',
    link: 'https://www.google.com/maps?cid=7327887939704951975',
    metaTitle: 'Urgent Care Lake Worth FL | Walk-In Clinic & Primary Care',
    metaDescription: 'Lake Worth urgent care and walk-in clinic. Fast, affordable care for injuries, illness, and physicals. No appointment needed. Serving Palm Beach State College, 33463, and nearby.',
    keywords: [
      'urgent care Lake Worth',
      'walk-in clinic Lake Worth',
      'Lake Worth medical clinic',
      'emergency care 33463',
      'primary care Lake Worth Road',
      'family doctor Lake Worth',
      'doctor near me Lake Worth open now',
      'cost of urgent care visit Lake Worth',
      'HCA urgent care alternative Lake Worth'
    ]
  },
  {
    name: 'Palm Springs',
    clinic: 'Palm Springs Primary & Urgent Care Center',
    address: '3460 S Congress Ave',
    city: 'Palm Springs',
    postalCode: '33461',
    phone: '561-223-8024',
    slug: 'palm-springs-primary-urgent-care-center',
    image: '/palmsprings.jpg',
    subimg: '/palmspring2.jpg',
    lat: 26.625354,
    lng: -80.088456,
    gmbCid: '8758270440044365995',
    gmbPlaceId: 'ChIJmwXvjQ_Y2IgRqwim2Y-gi3k',
    gmbUrl: 'https://www.google.com/maps?cid=8758270440044365995',
    link: 'https://www.google.com/maps?cid=8758270440044365995',
    metaTitle: 'Urgent Care Palm Springs FL | Walk-In Clinic & Primary Care',
    metaDescription: 'Palm Springs urgent care and walk-in clinic. Fast, affordable care for injuries, illness, and physicals. No appointment needed. Serving Greenacres, 33461, and nearby.',
    keywords: [
      'urgent care Palm Springs',
      'walk-in clinic Palm Springs',
      'Palm Springs medical clinic',
      'emergency care 33461',
      'primary care S Congress Ave',
      'family doctor Palm Springs',
      'urgent care near Greenacres FL',
      'doctor appointment today Palm Springs',
      'top rated walk in clinic Palm Springs'
    ]
  },
  {
    name: 'Lantana',
    displayName: 'Lantana / Jog Rd', // Branding allowed
    clinic: 'Lantana Primary & Urgent Care Center',
    address: '6169 Jog Rd Unit 4B',
    city: 'Lake Worth Beach', // GBP city - must use in NAP
    postalCode: '33463', // GBP ZIP
    phone: '561-223-8024',
    slug: 'lantana-primary-urgent-care-center',
    image: '/lakeworth.jpg',
    subimg: '/lantana.jpg',
    lat: 26.587833,
    lng: -80.1490233,
    gmbCid: '6581069000649192112',
    gmbPlaceId: 'ChIJ4d1n_Dcn2YgRsLIHWmOnVFs',
    gmbUrl: 'https://www.google.com/maps?cid=6581069000649192112',
    link: 'https://www.google.com/maps?cid=6581069000649192112',
    metaTitle: 'Urgent Care Lantana / Jog Rd | Walk-In Clinic & Primary Care',
    metaDescription: 'Lantana / Jog Rd urgent care and walk-in clinic in Lake Worth Beach, FL. Fast, affordable care for injuries, illness, and physicals. No appointment needed. Serving Boynton Beach, Lantana, Hypoluxo, and 33463.',
    keywords: [
      'urgent care Lantana',
      'walk-in clinic Lantana',
      'Lantana medical clinic',
      'emergency care 33463',
      'primary care Jog Road',
      'family doctor Lantana',
      'immediate care Lantana FL',
      'doctors office open saturday Lantana',
      'best urgent care Lantana',
      'urgent care Jog Rd Lake Worth Beach'
    ]
  }
]